name: Test Update Experience

on:
  push:
    branches:
      - main

jobs:
  test_update_experience:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run test script
      run: node test-script.js

    - name: Display updated data
      run: cat data.json
